require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system/businesses", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # System::Business. As you add validations to System::Business, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      System::Business.create! valid_attributes
      get system_businesses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      business = System::Business.create! valid_attributes
      get system_business_url(business)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_system_business_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      business = System::Business.create! valid_attributes
      get edit_system_business_url(business)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new System::Business" do
        expect {
          post system_businesses_url, params: { system_business: valid_attributes }
        }.to change(System::Business, :count).by(1)
      end

      it "redirects to the created system_business" do
        post system_businesses_url, params: { system_business: valid_attributes }
        expect(response).to redirect_to(system_business_url(System::Business.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new System::Business" do
        expect {
          post system_businesses_url, params: { system_business: invalid_attributes }
        }.to change(System::Business, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post system_businesses_url, params: { system_business: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested system_business" do
        business = System::Business.create! valid_attributes
        patch system_business_url(business), params: { system_business: new_attributes }
        business.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the system_business" do
        business = System::Business.create! valid_attributes
        patch system_business_url(business), params: { system_business: new_attributes }
        business.reload
        expect(response).to redirect_to(system_business_url(business))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        business = System::Business.create! valid_attributes
        patch system_business_url(business), params: { system_business: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system_business" do
      business = System::Business.create! valid_attributes
      expect {
        delete system_business_url(business)
      }.to change(System::Business, :count).by(-1)
    end

    it "redirects to the system_businesses list" do
      business = System::Business.create! valid_attributes
      delete system_business_url(business)
      expect(response).to redirect_to(system_businesses_url)
    end
  end
end
